sudo: false
cache: pip
language: python
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python-dbus
    - python-gtk2
    - python-wnck
    - python-xlib
install: "pip install coveralls"
script: nosetests
# TODO: Also run epydoc
after_success: coveralls
