dist: trusty
sudo: false
cache: pip
language: python
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python-dbus
    - python-epydoc
    - python-gtk2
    - python-wnck
    - python-xlib
install: "pip install coveralls"
script:
  - epydoc --config setup.cfg *.py
  - nosetests
after_success: coveralls
