safe: true
lsi: false
highlighter: rouge

# Stuff for _includes/contrib_box.html
bitcoin_uri: bitcoin:1Kp1i3nahunzzFs5a3mMF46uzca4oANH5C?label=QuickTile%20Donations
flattr_id: 674146
github_proj: ssokolow/quicktile
gittip_user: ssokolow
issues_url: https://github.com/ssokolow/quicktile/issues
paypal_btn_id: EFWRR7EAQ993S
