safe: true
lsi: false
pygments: true

# Stuff for _includes/contrib_box.html
bitcoin_uri: bitcoin:1J1wJPPshc7NsY8Dq89NzTqBoEUGhBphUK?label=QuickTile%20Tip%20Jar
flattr_id: 674146
github_proj: ssokolow/quicktile
gittip_user: ssokolow
issues_url: https://github.com/ssokolow/quicktile/issues
paypal_btn_id: EFWRR7EAQ993S
